FROM docker:29.7.2-cli@sha256:000bb62ff495f986c9f5578eb67cc2cb98b91138eda81d7762d5371eb8a497fe AS docker-cli

FROM golang:1.27.0-bookworm@sha256:484ef6066fa69acb059fdfeda7ba2b8f7391f2ef6abc6f9b8411e669ebd56466

ARG DAPPER_HOST_ARCH=amd64

ENV ARCH=${DAPPER_HOST_ARCH} \
    HOST_ARCH=${DAPPER_HOST_ARCH} \
    GO111MODULE=on \
    GOTELEMETRY=off \
    GOTOOLCHAIN=local \
    GOPROXY=https://proxy.golang.org \
    GOSUMDB=sum.golang.org \
    DAPPER_SOURCE=/go/src/github.com/PastureStack/network-plugin-manager \
    DAPPER_OUTPUT="./bin ./dist" \
    DAPPER_DOCKER_SOCKET=true \
    DAPPER_ENV="ARCH TAG REPO IMAGE_NAMESPACE VERSION_OVERRIDE DOCKER_BUILD_NETWORK"

COPY --from=docker-cli /usr/local/bin/docker /usr/bin/docker
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins/docker-buildx /usr/local/libexec/docker/cli-plugins/docker-buildx

RUN go version | grep -F 'go1.27.0' && \
    docker --version | grep -F 'Docker version 29.7.2,' && \
    docker buildx version | grep -F ' v0.36.1 '

WORKDIR ${DAPPER_SOURCE}
RUN git config --system --add safe.directory ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
