#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-s -w"
CGO_ENABLED=0 go build \
    -trimpath \
    -buildvcs=false \
    -ldflags "-buildid= -X main.VERSION=$VERSION $LINKFLAGS" \
    -o bin/network-plugin-manager
