#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_dir="$(cd "${script_dir}/.." && pwd)"
source "${script_dir}/version"
cd "${root_dir}"

mkdir -p bin
CGO_ENABLED=0 go build -mod=vendor -trimpath -buildvcs=false \
    -ldflags "-buildid= -s -w -X main.VERSION=${VERSION}" \
    -o bin/network-plugin-manager .
