#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

PACKAGES=". $(find -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

echo Running: go vet
go vet ${PACKAGES}
printf "%s\n" "Running supported validation: go vet and gofmt."
echo Running: gofmt
unformatted="$(find . -name '*.go' -not -path './.git/*' -not -path './vendor/*' -print0 \
    | xargs -0 -r gofmt -l -s)"
if [ -n "$unformatted" ]; then
    printf '%s\n' "$unformatted" >&2
    exit 1
fi
