#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

PACKAGES=". $(find -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

echo Running: go vet
go vet ${PACKAGES}
printf "%s\n" "Running supported validation: go vet and gofmt."
echo Running: gofmt
test -z "$(find . -name '*.go' | grep -v -e ./.git -e ./vendor | xargs gofmt -l -s | tee /dev/stderr)"
